### ISSUE TITLE
init fails if running in an existing TS project

### ISSUE THREAD

**Issue by beatfactor** [nightwatchjs/create-nightwatch#32]
If running `npm init nightwatch` in an existing TS project, the initialization fails with `SyntaxError`:

```
Installing the following packages:
- @types/nightwatch

Installing @types/nightwatch
Done! 

SyntaxError: Unexpected token } in JSON at position 438
    at JSON.parse (<anonymous>)
```

See also https://github.com/nightwatchjs/create-nightwatch/issues/33

**Comment by garg3133** [comment]
This seems to be due to an error in the `tsconfig.json` file of your existing TS project.

**Comment by beatfactor** [comment]
No, the `tsconfig.json` is fine.
