### ISSUE TITLE
node-geckodriver in version 4.0.0 fails to provide exectuable script

### ISSUE THREAD

**Issue by marcin-wosinek** [nightwatchjs/create-nightwatch#94]
Freshly generated project fails to run example tests:
https://github.com/nightwatchjs/nightwatch/issues/3754

It caused by the regresion new version of node-geckodriver:
https://github.com/webdriverio-community/node-geckodriver/issues/123

It could be fixed in create script by picking geckodriver@3.2.0

**Comment by garg3133** [comment]
This is fixed now with Nightwatch v3.

Starting with Nightwatch v3, webdriver packages are no longer required to be installed externally. A correct version of webdriver will now be downloaded automatically when you run a test (if not downloaded already), according to the version of the browser installed. This is made possible by [`selenium-manager`](https://www.selenium.dev/blog/2022/introducing-selenium-manager/).

If you are using an older version of Nightwatch and facing this issue, please make sure you install the version 3 of geckodriver: `npm i -D geckodriver@3`.
