### ISSUE TITLE
Combine `cd` command with test run commands.

### ISSUE THREAD

**Issue by garg3133** [nightwatchjs/create-nightwatch#96]
Currently, commands to run example tests appear as follows:

![image](https://github.com/nightwatchjs/create-nightwatch/assets/39924567/53890115-5990-4307-a50d-d7f83259e3a8)

But most of the time users skip the `cd` command. So, instead of specifying the `cd` command separately, it should be specified with the example commands as follows:

```sh
🚀 RUN EXAMPLE TESTS 

To run all examples, run:
  cd nightwatch-project
  npx nightwatch ./nightwatch/examples

To run a single example (ecosia.js), run:
  cd nightwatch-project
  npx nightwatch ./nightwatch/examples/basic/ecosia.js
```

**Comment by gpsinghsandhu** [comment]
@garg3133 Is this about updating the readme or do we want to update the setup instructions? For setup instructions, can you point me to the source for it.

**Comment by AutomatedTester** [comment]
looks like you're right @gpsinghsandhu !
