### ISSUE TITLE
Update example tests to make sure they work

### ISSUE THREAD

**Issue by AutomatedTester** [nightwatchjs/create-nightwatch#99]
There are quite a few example tests in this repo. We need to make sure they are working and if not update them

**Comment by gpsinghsandhu** [comment]
@AutomatedTester Can I take this up? If yes, can you point me to the actual examples you are talking about? I can only see some unit tests
![Uploading Screenshot 2023-10-20 at 10.51.04 PM.png…]()

**Comment by AutomatedTester** [comment]
The tests are pulled in from https://github.com/nightwatchjs/nightwatch-setup-tools

The main thing is making sure the js-examples ts-examples

**Comment by gpsinghsandhu** [comment]
@AutomatedTester  Created a pull request for this - https://github.com/nightwatchjs/nightwatch-setup-tools/pull/7. Please review.

**Comment by gpsinghsandhu** [comment]
@AutomatedTester Any update on this?

**Comment by gpsinghsandhu** [comment]
@AutomatedTester Since the pull request is merged now, can we close this?
